<a href="https://colab.research.google.com/github/divyaparadkar/pandas-/blob/main/S%26P_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy import sparse

In [3]:
matrix = np.array([[1,2,3],
  [4,5,6],
  [6,7,8]])

In [4]:
print("Original matrix: \n",matrix)

Original matrix: 
 [[1 2 3]
 [4 5 6]
 [6 7 8]]


In [5]:
print(sparse.dok_matrix(matrix))

  (0, 0)	1
  (0, 1)	2
  (0, 2)	3
  (1, 0)	4
  (1, 1)	5
  (1, 2)	6
  (2, 0)	6
  (2, 1)	7
  (2, 2)	8


In [7]:
print(sparse.dia_matrix(matrix))

  (2, 0)	6
  (1, 0)	4
  (2, 1)	7
  (0, 0)	1
  (1, 1)	5
  (2, 2)	8
  (0, 1)	2
  (1, 2)	6
  (0, 2)	3


In [8]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [9]:
print(np.linalg.inv(matrix))

[[ 4.50359963e+14 -1.12589991e+15  6.75539944e+14]
 [-9.00719925e+14  2.25179981e+15 -1.35107989e+15]
 [ 4.50359963e+14 -1.12589991e+15  6.75539944e+14]]
